services:
  - type: web
    name: aura
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn aura.wsgi:application --bind 0.0.0.0:$PORT