# Generated by Django 5.2.7 on 2025-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads/')),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
