# Generated by Django 5.2.7 on 2025-11-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfumes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfumes',
            old_name='files',
            new_name='img',
        ),
    ]
