# Generated by Django 5.2.7 on 2025-11-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_files_perfumes_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.TextField()),
                ('female', models.TextField()),
                ('en', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perfumes')),
            ],
        ),
    ]
