# Generated by Django 5.2.7 on 2025-11-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
