# Generated by Django 5.2.7 on 2025-11-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfumes',
            new_name='perfume',
        ),
        migrations.CreateModel(
            name='PerfumeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.perfume')),
            ],
        ),
    ]
