# Generated by Django 5.2.7 on 2025-11-10 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_perfumes_perfume_perfumedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumedetail',
            name='perfume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.perfume'),
        ),
    ]
