# Generated by Django 5.2.7 on 2025-11-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_perfumedetail_perfume'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfumedetail',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
