# Generated by Django 5.2.7 on 2025-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
