# Generated by Django 5.2.7 on 2025-11-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminlogin',
        ),
    ]
