# Generated by Django 6.0.2 on 2026-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_order_delivered_date_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('CARD', 'Card Payment'), ('UPI', 'UPI Payment'), ('WALLET', 'Wallet')], default='COD', max_length=20),
        ),
    ]
